test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -365,49 +365,49 @@ jobs:
 
 
 
-  run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
-      - image: cimg/node:13.8.0
-    steps:
-      # Checkout code from git
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Run migrations
-          command: |
-            cd backend
-            echo ENVIRONMENT=production > ".env"
-            echo TYPEORM_CONNECTION=postgres >> ".env"
-            echo TYPEORM_ENTITIES=./src/modules/domain/*/*/*.entity.ts >> ".env"
-            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
-            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
-            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
-            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
-            echo "npm install"
-            npm install
-            echo $?
-            echo "npm migrations"
-            npm run migrations > migrations_dump.txt
-            echo $?
-            echo "----------------------------------"
-            cat migrations_dump.txt 
-            echo "----------------------------------"
-      - run:
-          name: Send migration results to memstash
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              echo 'Migrated successfully'
-              curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-            else:
-              echo 'Migration failed'
-              curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
-            fi
+  # run-migrations:
+  #   docker:
+  #     # Docker image here that supports NodeJS
+  #     - image: cimg/node:13.8.0
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     - attach_workspace:
+  #         at: .
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           echo ENVIRONMENT=production > ".env"
+  #           echo TYPEORM_CONNECTION=postgres >> ".env"
+  #           echo TYPEORM_ENTITIES=./src/modules/domain/*/*/*.entity.ts >> ".env"
+  #           echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
+  #           echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+  #           echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+  #           echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+  #           echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+  #           echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+  #           echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+  #           echo "npm install"
+  #           npm install
+  #           echo $?
+  #           echo "npm migrations"
+  #           npm run migrations > migrations_dump.txt
+  #           echo $?
+  #           echo "----------------------------------"
+  #           cat migrations_dump.txt 
+  #           echo "----------------------------------"
+  #     - run:
+  #         name: Send migration results to memstash
+  #         command: |
+  #           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+  #           then
+  #             echo 'Migrated successfully'
+  #             curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+  #           else:
+  #             echo 'Migration failed'
+  #             curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
+  #           fi
   
   deploy-frontend:
    # Docker 
