test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -306,43 +306,91 @@ jobs:
 #       # Here's where you will add some code to rollback on failure      
      #- destroy-environment
 
+  # run-migrations:
+  #   docker:
+  #     # Docker image here that supports NodeJS
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #   # Checkout code from git
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           # your code here
+  #           sudo apt install -y tar gzip curl
+  #           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+  #           unzip -qq awscliv2.zip
+  #           sudo ./aws/install
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           npm run migrations > migrations_dump.txt
+           
+  #     - run:
+  #         name: Send migration results to memstash
+  #         command: |
+  #           echo "Querying buc value https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}"
+  #           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+  #           then
+  #           echo 'Migrated successfully'
+  #           curl --insecure https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+  #           else:
+  #           echo 'Migration failed'
+  #           curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
+  #           fi
+  #     #- destroy-environment 
+  #     #- revert-migrations
+  #    # Here's where you will add some code to rollback on failure      
+  
   run-migrations:
     docker:
       # Docker image here that supports NodeJS
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
-    # Checkout code from git
+      # Checkout code from git
       - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-            sudo apt install -y tar gzip curl
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip -qq awscliv2.zip
-            sudo ./aws/install
+      - attach_workspace:
+          at: .
       - run:
           name: Run migrations
           command: |
             cd backend
+            echo ENVIRONMENT=production > ".env"
+            echo TYPEORM_CONNECTION=postgres >> ".env"
+            echo TYPEORM_ENTITIES=./src/modules/domain/*/*/*.entity.ts >> ".env"
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+            echo "npm install"
             npm install
+            echo $?
+            echo "npm migrations"
             npm run migrations > migrations_dump.txt
-           
+            echo $?
+            echo "-------------------------------"
+            cat migrations_dump.txt 
+            echo "------------------------------"
       - run:
           name: Send migration results to memstash
           command: |
-            echo "Querying buc value https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}"
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-            echo 'Migrated successfully'
-            curl --insecure https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              echo 'Migrated successfully'
+              curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             else:
-            echo 'Migration failed'
-            curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
+              echo 'Migration failed'
+              curl https://kvdb.io/N1fybErqdSD264W13w349U/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
             fi
-      #- destroy-environment 
-      #- revert-migrations
-     # Here's where you will add some code to rollback on failure      
+    # Here's where you will add some code to rollback on failure    
+      - slack/notify:
+          event: fail
+          template: basic_fail_1     
 
   deploy-frontend:
    # Docker 
