final commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -261,7 +261,7 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure  
-      - destroy-environment
+      # - destroy-environment
           #workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
   
   configure-infrastructure:
@@ -299,7 +299,7 @@ jobs:
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
-      - destroy-environment
+      # - destroy-environment
            
 #       # Here's where you will add some code to rollback on failure      
      #- destroy-environment
@@ -456,12 +456,12 @@ jobs:
             #if curl -s $API_URL/api/status | grep "ok"
             if curl ${URL} | grep "Welcome"
               then
-                exit 0
+                exit 1
               else
                 exit 1
               fi
       - destroy-environment
-      # - revert-migrations:
+      - revert-migrations
 
       # - destroy-environment
       # - revert-migrations
@@ -548,8 +548,8 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cleanup:
+      #     requires: [cloudfront-update]
       # - cleanup
 
       
